apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-service
  labels:
    app: os-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: os-service
  template:
    metadata:
      labels:
        app: os-service
    spec:
      containers:
        - name: os-service
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/garage-os-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: os-service-config
                  key: database-host
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: os-service-secrets
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os-service-secrets
                  key: database-password
            - name: DATABASE_NAME
              value: 'os_service'
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: fiap-garage-secret
                  key: RABBITMQ_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fiap-garage-secret
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /os/health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /os/health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: '128Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '200m'
---
apiVersion: v1
kind: Service
metadata:
  name: os-service
spec:
  selector:
    app: os-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 31001
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: os-service-config
data:
  database-host: postgres-os-service
